### ISSUE TITLE
 install-command does not work if the install-command contains apostrophe `"`

### ISSUE THREAD

**Issue by WolfSoko** [nrwl/ci#10]
The input `install-command` of the `nx-cloud-main.yml@v0.2` workflow does fail when the `install-command` input contains aphostophe. 

Error Message:
```
Run if [ -n "echo "Test"
... 
/home/runner/work/_temp/f144c54f-e9f8-48bd-9d58-abcdef123.sh: line 1: [: too many arguments
```

e.g. in your ci.yaml: 
```yaml
jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.2
    with:
      node-version: ${{ github.env.NODE_VERSION }}
      install-command: |
        echo "Test"
        sudo apt-get upgrade -y
        npm ci
        ...
```

The problematic code line seems to be: https://github.com/nrwl/ci/blob/c29f238454e5782c59e60de1143f7593346e04f1/.github/workflows/nx-cloud-main.yml#L137

Apostrophe inside the `install-command` ends the if statement string and leads to unpredictable behavior.
