### ISSUE TITLE
Workflow hangs for full timeout if there are no detectable changes

### ISSUE THREAD

**Issue by electrichead** [nrwl/ci#30]
It appears as though if `affected` detects no changes, the agents are brought up and then timeout after the default 60mins.

The PR here had a change to several files that were in a folder that is in `.nxignore`

Is there something we need to do to short-circuit this?
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/453966/193883379-a62a8dfd-f692-4afe-8d13-ff16cdfb3178.png">

```yaml
name: 'Affected commands'

on:
  pull_request:
    branches: [master]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
  NODE_OPTIONS: '--max_old_space_size=4096'
  CYPRESS_INSTALL_BINARY: 0

jobs:
  main:
    name: Nx Cloud Main
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.4
    with:
      main-branch-name: 'master'
      node-version: '14.17.0'
      npm-version: '6.14.17'
      yarn-version: '1.22.18'
      parallel-commands-on-agents: |
        npx nx-cloud record -- npx nx format:check
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3

  agents:
    name: Nx Cloud Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.4
    with:
      number-of-agents: 12
      node-version: '14.17.0'
      npm-version: '6.14.17'
      yarn-version: '1.22.18'
```
