### ISSUE TITLE
Passing Env vars into action

### ISSUE THREAD

**Issue by lukasburns** [nrwl/ci#44]
Hi, thanks for this action! looks amazing.
Is there any way of passing a env var into the action?
I would like to pass an npm token as an env var into the action so when it build it can read packages from a private registry.

**Comment by sebpalluel** [comment]
Same, i'm looking to create a .env file from a secrets as such:

```yml
jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.9
    with:
      init-commands: |
        echo "${{ secrets.ENV_FILE }}" > .env
```
But i've got this error: `The workflow is not valid. .github/workflows/ci.yml (Line: 18, Col: 22): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.ENV_FILE`

According to the doc, I can't use `environment-variables` for that purpose either.

I really need to find a solution as I want to open source a project but I don't want to leak my API keys...
