### ISSUE TITLE
Error when changing to v0.11.0

### ISSUE THREAD

**Issue by fnoquiq** [nrwl/ci#48]
When changing version 0.10 to 0.11 of the action, github actions started showing errors

![Captura de tela de 2022-12-06 12-16-40](https://user-images.githubusercontent.com/11557379/205950860-b4d15ea1-5c53-48ed-8c44-cffda7b9d641.png)

Here is the error shown by github actions

![Captura de tela de 2022-12-06 12-15-48](https://user-images.githubusercontent.com/11557379/205950652-2924eead-6408-4c90-ba7e-d3260ca501ff.png)

---

My workflow file

```yml
name: CI - Nx Cloud

on:
  pull_request: 
    branches: [some branchs]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_CLOUD_DISTRIBUTED_EXECUTION_STOP_AGENTS_ON_FAILURE: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    permissions:
      contents: 'read'
      actions: 'write'

    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11
    with:
      number-of-agents: 3
      parallel-commands-on-agents: |
        yarn nx affected --target=c1 --parallel=3
        yarn nx affected --target=c2 --parallel=3
        yarn nx affected --target=c3 --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11
    with:
      number-of-agents: 3

```
