### ISSUE TITLE
[Feature Request]: Add Init Commands Option for Agents

### ISSUE THREAD

**Issue by ryanbas21** [nrwl/ci#5]
We need to add domains to our `/etc/hosts` file in order for our E2E to run successfully.

We have to spin up a web and api server, which we need to test on actual domains.

It appears, that agents run on different machines (I'm not a CI expert, but this seems reasonable) than the `main` job runs on (which makes sense). So I need each agent that is running an E2E (at least for this E2E job), to have these `/etc/hosts` domains available.

I have been changing the /etc/hosts file like so: 
`sudo echo "127.0.0.1 sdkapp.example.com auth.example.com api.example.com user.example.com" | sudo tee -a /etc/hosts` 

It would be great if we have an option for `init-commands: |` in agent config as well.

Something like this:

```yml
agents:
    name: Forgerock CI Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.2
    with:
      init-commands: |
      sudo echo "127.0.0.1 sdkapp.example.com auth.example.com api.example.com user.example.com" | sudo tee -a /etc/hosts
      number-of-agents: 3
```  
      
 For my understanding: In this scenario, I think only the agent needs to edit to the /etc/hosts config file, and the "main" job in this instance would not need it because its not really "running" the command. Is this correct?
