### ISSUE TITLE
runs-on config is not working as expected

### ISSUE THREAD

**Issue by daniel-zero** [nrwl/ci#61]
I tried to use larger runners to speed up our nx builds even more. GitHub provides us a list of large runners for example: `ubuntu-latest-16-cores`.

<img width="813" alt="Screenshot 2023-02-08 at 09 53 44" src="https://user-images.githubusercontent.com/95087607/217481545-c5c910d2-1f97-4e88-bcd3-ecd6dda3245f.png">

When I set this name in the ci-config, the build will fail. It looks like it is not possible to define the requested runner by name. I'm missing something in my config?

```yml
name: NX Cloud

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11
    if: github.event.pull_request.draft == false
    with:
      number-of-agents: 3
      runs-on: ubuntu-latest-16-cores
      main-branch-name: 'master'
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx run-many --all --target=test --parallel=3 --ci --code-coverage --coverageReporters=lcov
        npx nx affected --target=build --parallel=1
      final-commands: |
        npx nx-cloud record node ./tools/scripts/coverageMerger.js
      artifacts-path: |
        coverage/lcov.info
      artifacts-name: coverage-report

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11
    if: github.event.pull_request.draft == false
    with:
      number-of-agents: 3
      runs-on: ubuntu-latest-16-cores

```
