### ISSUE TITLE
Error when connecting to Nx Cloud. Code: 404

### ISSUE THREAD

**Issue by zaunermax** [nrwl/ci#65]
Lately we've been getting weird cloud errors where the main job times out with a weird 404 error from nx-cloud. The app shows in the text message that the runs went through, when logging into the cloud the runs also seem to go through but the action itself fails with this error:
![image](https://user-images.githubusercontent.com/15246773/218437014-5b2d1cc0-b145-4785-991e-aa73746eea90.png)

Sadly I've not been able to create a test repo to reproduce this error 🤔 If you need any additional info let me know. 

Our config:
```
name: nrwl-nx-ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      number-of-agents: 2
      node-version: 18.14.0
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3 --maxWarnings=0
        npx nx affected --target=build --parallel=3 -c prod --prod

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 2
      node-version: 18.14.0
```

Lastly, is there a way to completely purge the cache of nx cloud? 🤔 I am aware of `--skip-nx-cache` but there is not command afaik that just resets one nx cloud cache?
