### ISSUE TITLE
nx-cloud-main: forward secrets/env for commands running parallel

### ISSUE THREAD

**Issue by muametgrooby** [nrwl/ci#71]
Hello, I am using ``nx-cloud-main`` and I have a use case where I need to pass a secret into a command running in parallel. It is currently impossible, can we get a way to set internal environment variables from outside or allow ``nx-cloud-main`` to use secrets?

I am using ``@nx-tools/nx-container`` and they require ``secrets.GITHUB_TOKEN``

**Comment by kapik** [comment]
Hey 👋
I have the same need but for others env var (like deployment secrets).

Wouldn't it be possible to use the workflow envs like that?
```
env:
  FOO: ${{ secrets.BAR }}

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    ...
```

What would be the best alternative if this is not possible?
