### ISSUE TITLE
Add the possibility to set a container image option

### ISSUE THREAD

**Issue by yannickmonney** [nrwl/ci#75]
In order to have the possibility to use a specific container image, could we add the container image option? 

```yml
jobs:
  job:
    container:
      image: ${{ ... }}
```

For more information, see: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

Additionally, `timeout-minutes` could we add this one too?
