### ISSUE TITLE
Specifying a custom runner with runs-on fails

### ISSUE THREAD

**Issue by stijnvn** [nrwl/ci#87]
Specifying a custom runner with `runs-on` fails with the following error message:

```
Called workflows cannot be queued onto self-hosted runners across organisations/enterprises. Failed to queue this job. Labels: '8-core_runner'.
```

Any idea what could be wrong or how to fix this?

The github actions config:

```
name: CI

on:
  push:
    branches:
      - master
      - staging
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      runs-on: 8-core_runner
      main-branch-name: master
      parallel-commands: |
        npx nx-cloud record -- nx format:check --all
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=4 --maxWarnings=0
        npx nx affected --target=test --parallel=4 --ci
        npx nx affected --target=build --parallel=4 --prod

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      runs-on: 8-core_runner
      number-of-agents: 8
```
