### ISSUE TITLE
Support setting registry-url and scope for private packages

### ISSUE THREAD

**Issue by kdawgwilk** [nrwl/ci#91]
We currently have this step in our workflow that we are trying to migrate to NxCloud DTE 
```yml
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@myorg'
```
The current workflow does support node-version and cache but does not support the `registry-url` and `scope` params.  There is also support for setting the `NPM_TOKEN` secret but I am struggling to see how that can even be used without being able to set these.  Could we set these using a `.npmrc` file in the root of our repo?
