### ISSUE TITLE
Is this task compatible with Nx17?

### ISSUE THREAD

**Issue by asgerjensen** [nrwl/ci#95]
After upgrading to NX17, my build job fails to run  with "To use Distributed Task Execution, your default task runner configuration must    use the "nx-cloud" task runner."

For background: I'm using nx-cloud only on the CI server. Nx migrate removed the `taskRunnerOptions` from nx.json, so not really sure why it would need to set it again?

SHORT FORM:
Is this shared action known to be compatible with nx17?

LONG FORM:
I've bumped to run on 0.14.0 of this action, but i get

For *Start Nx Agent 1/2/3*
```
Run npx nx-cloud start-agent
  

 >  NX   Starting an agent for running Nx tasks


 >  NX   Invalid Task Runner Configuration

   To use Distributed Task Execution, your default task runner configuration must
   use the "nx-cloud" task runner.
   
   This can be adjusted in "nx.json".
```

Under "Run any configured install commands" it logs

```

Run npm ci --prefer-offline --audit false --legacy-peer-deps 
  npm ci --prefer-offline --audit false --legacy-peer-deps 
  npm run postinstall
  npx nx report
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
    NX_BRANCH: [2](https://github.com/<ORG>/<REPO>/actions/runs/6958272621/job/18932964541#step:15:2)54
    NX_CLOUD_ACCESS_TOKEN: ***
    NX_CLOUD_AUTH_TOKEN: 
    NPM_TOKEN: 
    VOLTA_HOME: /opt/hostedtoolcache/volta/1.1.1/x64
npm WARN deprecated raven@2.6.4: Please upgrade to @sentry/node. See the migration guide https://bit.ly/[3](https://github.com/ORG/REPO/actions/runs/6958272621/job/18932964541#step:15:3)ybOlo7
npm WARN deprecated intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
npm WARN deprecated @types/reflect-metadata@0.1.0: This is a stub types definition for reflect-metadata (https://github.com/rbuckton/ReflectDecorators). reflect-metadata provides its own type definitions, so you don't need @types/reflect-metadata installed!
npm WARN deprecated @slack/events-api@3.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> REPO@17.0.0 postinstall
> node ./decorate-angular-cli.js


 >  NX   Decoration of the Angular CLI is deprecated and will be removed in a future version

   Please replace usage of "ng <command>" in any scripts, particularly for CI, with "nx <command>"


 >  NX   Angular CLI has been decorated to enable computation caching.


added 2687 packages in 1m

358 packages are looking for funding
  run `npm fund` for details

> REPO@17.0.0 postinstall
> node ./decorate-angular-cli.js


 >  NX   Decoration of the Angular CLI is deprecated and will be removed in a future version

   Please replace usage of "ng <command>" in any scripts, particularly for CI, with "nx <command>"


 >  NX   Angular CLI has been decorated to enable computation caching.


 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : linux-x6[4](https://github.com/ORG/REPO/actions/runs/6958272621/job/18932964541#step:15:4)
   npm    : 9.8.1
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/angular        : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/plugin         : 17.1.3
   @nx/storybook      : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : [5](https://github.com/ORG/REPO/actions/runs/6958272621/job/18932964541#step:15:5).2.2
   ---------------------------------------
   Community plugins:
   @currents/nx       : 0.2.1
   @ngneat/spectator  : 10.0.1
   @storybook/angular : [7](https://github.com/ORG/REPO/actions/runs/6958272621/job/18932964541#step:15:7).5.3
   ng-mocks           : 14.[12](https://github.com/ORG/REPO/actions/runs/6958272621/job/18932964541#step:15:12).1
   ---------------------------------------
   Local workspace plugins:



```

My tasks:
``` 

main:
    needs:
      - install
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 3
      install-commands: npm ci --prefer-offline --audit false --legacy-peer-deps && npm run postinstall
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="e2e" --agent-count=3
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --ci  --base=remotes/origin/main --parallel=3 --runInBand --exclude integration-tests components storefront-b2c feed-generator
        npx nx affected --target=server  --parallel=3
        npx nx affected --target=build --parallel=3
  # check server side builds as well as regular builds, to capture any broken services
  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.14.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 3
      install-commands: |
        npm ci --prefer-offline --audit false --legacy-peer-deps 
        npm run postinstall
        npx nx report
```
