### ISSUE TITLE
Github CI - no such file or directory package.json

### ISSUE THREAD

**Issue by jh3ady** [nrwl/ci#96]
Hello,

I used the command line : 

```bash
nx g ci-workflow
```

to generate my github workflow.

It generated me a `ci.yml` file where I added my secret `NX_CLOUD_ACCESS_TOKEN`

```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
    with:
      main-branch-name: main
      number-of-agents: 3
      init-commands: |
        pnpm exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        pnpm exec nx-cloud record -- pnpm exec nx format:check
      parallel-commands-on-agents: |
        pnpm exec nx affected --target=lint --parallel=3
        pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
        pnpm exec nx affected --target=build --parallel=3
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
    with:
      number-of-agents: 3
```

When the pipeline runs I receive this error during `Install PNPM` step

```
Run pnpm/action-setup@v2
  with:
    package_json_file: /home/runner/work/myrepo/myrepo/package.json
    dest: ~/setup-pnpm
    run_install: null
    standalone: false
  env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
    NX_BRANCH: 4
    NX_CLOUD_ACCESS_TOKEN: ***
    NX_CLOUD_AUTH_TOKEN: 
    NPM_TOKEN: 
    NX_BASE: abb15dd8634ea8a39afef3e0510f9[2](https://github.com/sueno-ltd/myrepo/actions/runs/7383009232/job/20083548144#step:7:2)458ffabf76
    NX_HEAD: dc52fca6dbde92cf8[3](https://github.com/sueno-ltd/myrepo/actions/runs/7383009232/job/20083548144#step:7:3)72369f0c2a1f8ebec6dd8d
    VOLTA_HOME: /opt/hostedtoolcache/volta/1.1.1/x6[4](https://github.com/sueno-ltd/myrepo/actions/runs/7383009232/job/20083548144#step:7:4)
Running self-installer...
  [Error: ENOENT: no such file or directory, open '/home/runner/work/myrepo/myrepo/home/runner/work/myrepo/myrepo/package.json'] {
    errno: -2,
  Error: Error: ENOENT: no such file or directory, open '/home/runner/work/myrepo/myrepo/home/runner/work/myrepo/myrepo/package.json'
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/runner/work/myrepo/myrepo/home/runner/work/myrepo/myrepo/package.json'
  }
  ```
  
It looks like the current path is duplicated

Thank you in advance for your help
